### ISSUE TITLE
No tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [sbrink/vscode-elm#19] opened 2015-12-25 16:59 UTC
> You can hover over a function and get the signature and comment.

This is not the case. VSCode 0.10.6, latest vscode-elm.

**Comment by corymickelson** [comment] 2016-01-16 20:24
error's in console when trying to get hover info
<img width="400" alt="screen shot 2016-01-16 at 12 22 23 pm" src="https://cloud.githubusercontent.com/assets/8325902/12374297/fce67e36-bc4b-11e5-918f-48b8c74e52f9.png">

**Comment by ccapndave** [comment] 2016-01-26 11:18
I also can't get the tooltips to pop up.  I debugged and it looks like `oracle.GetOracleResults` in `elmInfo.ts` is returning `null` every time I hover over something, causing `result.length` to fail.

**Comment by stkb** [comment] 2016-01-26 20:15
This is (partially) caused by some weird code in [elmOracle.ts](https://github.com/sbrink/vscode-elm/blob/6e9e615efa5405164e76298e9093aabd5b416b05/src/elmOracle.ts#L24-L34):

``` typescript
p = cp.exec('node ' + oracle, { cwd: cwd }, (err: Error, stdout: Buffer, stderr: Buffer) => {
  try {
    if (err) {
      return resolve(null);
    }
    let result: IOracleResult[] = JSON.parse(stdout.toString());
    resolve(result);
  } catch (e) {
    reject(e);
  }
});
```

The try-catch is weirdly placed, and if an error occurs calling Oracle, the promise is resolved with ```null``` passed on, instead of rejecting. The next handler then chokes on the null.

I think I'd like to write a single wrapper for calling external processes, to fix this and a couple of other issues.

**Closed** 2016-02-12 02:54 UTC
